# Generated by Django 5.1.7 on 2025-03-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_figurine_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='figurine',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
