# Generated by Django 5.1.7 on 2025-03-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_figurine_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='figurine',
            name='scale',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
