# Generated by Django 5.1.7 on 2025-03-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_alter_figurine_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figurine',
            name='scale',
            field=models.CharField(blank=True, choices=[('1/12', '1/12 Scale'), ('1/8', '1/8 Scale'), ('1/7', '1/7 Scale'), ('1/6', '1/6 Scale'), ('1/4', '1/4 Scale')], max_length=10, null=True),
        ),
    ]
