# Generated by Django 5.1.7 on 2025-03-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_alter_figurine_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='figurine',
            name='category',
            field=models.CharField(blank=True, choices=[('Scale', 'Scale'), ('Nendoroids', 'Nendoroids'), ('Figma', 'Figma'), ('Pop Up Parade', 'Pop Up Paradee'), ('Prize Figures', 'Prize Figures')], max_length=13, null=True),
        ),
    ]
