# Generated by Django 5.1.7 on 2025-03-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_figurine_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figurine',
            name='category',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('Nendoroids', 'Nendoroids'), ('Figma', 'Figma'), ('Pop Up Parade', 'Pop Up Paradee'), ('Prize Figures', 'Prize Figures')], max_length=13, null=True),
        ),
    ]
