# Generated by Django 5.1.7 on 2025-03-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_alter_figurine_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='figurine',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='figurine',
        ),
        migrations.AddField(
            model_name='collection',
            name='figurines',
            field=models.ManyToManyField(to='collection.figurine'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='figurines',
            field=models.ManyToManyField(to='collection.figurine'),
        ),
    ]
